version: "3"
services:
  nuxt:
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - 3000:3000
    env_file:
      - ./.prod.env
    networks: 
      - app-tier

networks: 
  app-tier: